### ISSUE TITLE
Cauldrons can not be filled with water in the nether.

### ISSUE THREAD

**Issue by PieCreeper12** [ceskyDJ/NetherWater#22]
Normally, you can fill a cauldron with water in the Nether. However, this plugin causes water to go on top of the cauldron instead of in it, making it impossible to do so.
![image](https://user-images.githubusercontent.com/13491668/131193418-293be23b-ac5e-4cfb-ae7c-493c943935ed.png)

**Comment by ceskyDJ** [comment]
Hello, I'm sorry for such a big delay. I completely missed your issue and I had found it today, when I was browsing this repository. I'll try to resolve this issue shortly but it probably won't be before a half of December, because of school projects. Thanks for posting this. Have a nice day.

**Comment by PieCreeper12** [comment]
Big is an understatement lmao. I'm kidding. Thanks for responding!

**Comment by ceskyDJ** [comment]
I know... I'll try resolve it as sooner as possible. It couldn't be such a huge problem.

**Comment by ceskyDJ** [comment]
I looked at it and find that I didn't implement features around cauldrons at all. I'm sorry about that. I have a fix prepared and waiting for the next release. Except of the fix it will contain smoke effect for water in cauldrons and water disappearing for it, too. I hope it will be all implemented in the right way after this update. If you find something else, let me know, please.

**Comment by ceskyDJ** [comment]
The next update will be released today or tomorrow, I promise.

**Comment by ceskyDJ** [comment]
@PieCreeper12, new version has been released, so you can download it and test it. Let me know, if you find some bug, please.
