### ISSUE TITLE
Problem with measuring distance of players from different worlds

### ISSUE THREAD

**Issue by DuneSciFye** [ceskyDJ/NetherWater#26]
This is constantly being spammed in the console:
https://pastebin.com/siTyttjw

**Found bugs:**
- [x] Measuring player distances (in NetherWater.java) over two worlds (it's of course impossible)
- [x] What about automatically loaded chunks (by nether portal or some plugins?) - there could be no player or different player

**Comment by ceskyDJ** [comment]
Hi, thanks for your bug report. It looks like a problem with worlds. What plugin do you use for managing worlds? Could you send me a list of worlds you are using? What Skyblock plugin do you use? Thanks for replying. Have a nice day.

**Comment by ceskyDJ** [comment]
Hmm, it's interesting. Is there some kind of autoloaded chunk in some of worlds from the log?

**Comment by DuneSciFye** [comment]
Here is a list of plugins I'm using:
Plugins (55): AdvancedEnchantments, AntiDrop, AuctionHouse, AutoPickup, BambooCollisionFix, BlockSpawnerEXP*, BossShopPro, BuycraftX, Citizens, CoinFlipper*, CoreProtect, CrazyCrates, DeluxeMenus, DiscordSRV, Essentials, EssentialsSpawn, GadgetsMenu, GriefPrevention, GSit, HolographicDisplays, HolographicExtension, Hub*, InvSeePlusPlus, JetsHoppers, JetsMinions, LibsDisguises, LimitedUses*, LiteBans, LuckPerms, mcMMO, Multiverse-Core, Multiverse-Inventories, NetherWater, PlaceholderAPI, PlayerPoints, Playtimes*, ProtocolLib, Quests, Scoreboard-revision*, ShopGUIPlus, ShopGUIPlus-SellGUI, SignShop, StaffTools*, SuperiorSkyblock2, Themis, ThirdCurrency*, TradeSystem, UpgradeableSpawners, Vault, VentureChat, WildChests, WorldChangeScreenRemover, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by DuneSciFye** [comment]
I use Multiverse Core for managing worlds. I use SuperiorSkyblock2 for skyblock. A list of worlds are: 
Superiorworld_nether - NETHER
Skyblock - NORMAL
world - NORMAL
Skyblock_nether - NETHER
Superiorworld - NORMAL
Superiorworld_the_end - THE_END
Skyblock_the_end - THE_END
SkyBlock - UNLOADED
SkyBlock_nether - UNLOADED
SuperiorWorld_the_end - UNLOADED
SkyBlock_the_end - UNLOADED
SuperiorWorld_nether - UNLOADED
event - UNLOADED

**Comment by DuneSciFye** [comment]
I did the previous list using /mv list, it seems to be a bit broken. Here's a correct list:
Skyblock
Skyblock_nether
Skyblock_the_end
Superiorworld
Superiorworld_nether
Superiorworld_the_end
world

**Comment by ceskyDJ** [comment]
Thanks for your answer. Is it running on a public server? It will be good to run the plugin with `debug: true` set up in config (it shouldn't need reload nor restart, only save edited file) and send me a part of generated log in console. If it's a public server, it should be done when there is a minimal number of players and after doing this return back `debug: false`.

Log should contain coordinates of activated dispensers. If you can get it from the log, teleport to the coordinates and take a some screenshots, please. It could help a lot. If you take screenshots, give me a log, too. It can be useful, too.

**Comment by DuneSciFye** [comment]
Sorry for the delayed response, but I'm having issues with simply placing and breaking in the nether, so once I sort that out I'll get back to you. My discord is DuneSciFye#0326 if you want to contact me there

**Comment by ceskyDJ** [comment]
You probably sent me a bad Discord identifier (one number is missing). If you want to help, you can use my Discord server created for my plugins: https://discord.gg/XFDFXX94pd
